version: "3"

services:
  backend:
    build: ./backend

    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=postgresql://user:password@database:5432/santa
      - JWT_SECRET=yourjwtsecret

    depends_on:
      - database

    restart: unless-stopped
    
    networks:
      - santa-network
    
  database:
    image: postgres

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=santa
    
    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - santa-network

  frontend:
    build: ./frontend

    networks:
      - santa-network
  
  nginx:
    image: nginx:latest

    ports: 80:80

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - backend
      - frontend

    networks:
      - santa-network

networks:
  santa-network:
    driver: bridge

volumes:
  db_data:
