// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Participant struct {
	ID      int64
	UserID  int64
	RoomID  int64
	Wish    pgtype.Text
	GivesTo pgtype.Int8
}

type Room struct {
	ID              int64
	OwnerID         int64
	Name            pgtype.Text
	Description     pgtype.Text
	MaxParticipants pgtype.Int4
	CreatedAt       pgtype.Timestamp
}

type User struct {
	ID           int64
	Name         pgtype.Text
	Username     string
	Password     string
	RegisteredAt pgtype.Timestamp
}
