// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Participant struct {
	ID     int32
	UserID int32
	RoomID int32
	Wish   pgtype.Text
}

type Room struct {
	ID              int32
	OwnerID         int32
	Name            pgtype.Text
	Description     pgtype.Text
	MaxParticipants pgtype.Int4
	CreatedAt       pgtype.Timestamp
}

type User struct {
	ID           int32
	Name         pgtype.Text
	Username     string
	Password     string
	RegisteredAt pgtype.Timestamp
}
