// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participants (
    user_id,
    room_id,
    wish
) VALUES (
    $1,
    $2,
    $3
)
`

type CreateParticipantParams struct {
	UserID int32
	RoomID int32
	Wish   pgtype.Text
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.Exec(ctx, createParticipant, arg.UserID, arg.RoomID, arg.Wish)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, user_id, room_id, wish FROM participants
WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id int32) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoomID,
		&i.Wish,
	)
	return i, err
}

const getUserParticipations = `-- name: GetUserParticipations :many
SELECT id, user_id, room_id, wish FROM participants
WHERE user_id = $1
`

func (q *Queries) GetUserParticipations(ctx context.Context, userID int32) ([]Participant, error) {
	rows, err := q.db.Query(ctx, getUserParticipations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoomID,
			&i.Wish,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
